language: python
python:
 - "3.6"

# command to run tests
script:
 - python -m unittest TestTriangle

install:
  - pip install codecov

script:
  - coverage run TestTriangle.py

after_success:
  - codecov
